language: python
python: 3.5
sudo: required

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

before_install:
  - wget http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - tar xvf ffmpeg-git-64bit-static.tar.xz
  - sudo cp ffmpeg-git-20160706-64bit-static/ffmpeg /usr/local/bin/
  - sudo cp ffmpeg-git-20160706-64bit-static/ffprobe /usr/local/bin/

install:
  - pip install tox
script:
  - tox -e $TOX_ENV
