language: python
python: 3.5
sudo: required

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pylint

before_install:
  - wget http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - tar xvf ffmpeg-git-64bit-static.tar.xz
  - dir=$(find . -type d -name "ffmpeg-git-*-64bit-static")
  - sudo cp $dir/ffmpeg /usr/local/bin/
  - sudo cp $dir/ffprobe /usr/local/bin/

install:
  - pip install tox
script:
  - tox -e $TOX_ENV
